### ISSUE TITLE
Make the code repository pattern compliant

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-second-opinion#14]
Looking good so far team! We need to do a few other things to make this a "code pattern":

1. [x] Create a thorough README.md
2. [x] Create a wiki to draft IBMCode content
3. [x] Add an architectural diagram
4. [x] Add Deploy to IBM Cloud support
5. [ ] Create a video
6. [x] Create a blog

See https://github.com/IBM/watson-discovery-ui as an example.

**Comment by stevemar** [comment]
Architecture and README completed, yay!

**Comment by stevemar** [comment]
@horeaporutiu @AnthonyAmanse would be great to have a basic linting CI job for this repo!

**Comment by stevemar** [comment]
@AnthonyAmanse is a "deploy to bluemix" button do-able with the proposed k8s flow?

**Comment by AnthonyAmanse** [comment]
@stevemart I'll take a look into it

**Comment by stevemar** [comment]
Marking this as closed now that the SLAM is over.

**Comment by horeaporutiu** [comment]
Will create video and blog next week. Have a different demo that I need to work on until next Monday, but after 4/2 I will finish up blog and video for this project.

**Comment by stevemar** [comment]
@horeaporutiu I believe anything had created the blog already. I encourage you to do a quick video explaining what the code pattern is, how to deploy it, and how to run it to generate some output. cc @sanjeevghimire

**Comment by horeaporutiu** [comment]
@stevemart I will finish video and blog soon. Blog is pretty much done.

**Comment by stevemar** [comment]
@horeaporutiu Anthony published one [here](https://developer.ibm.com/code/?p=32974&preview=1&_ppp=70574cc818) but the link has expired. Either way, if your blog is done then we can always have two, not an issue.

**Comment by horeaporutiu** [comment]
Okay, will coordinate with @AnthonyAmanse on this.
