### ISSUE TITLE
Building and Deploying Failed

### ISSUE THREAD

**Issue by sanjeevghimire** [IBM/watson-second-opinion#35]
Readme is not clear on building and deploying. there are few missing steps. Below are some suggested changes:
1. In the install docker section we can add “If you get docker login error, try sudo docker login use sudo docker login”
2. its good to mention 2 steps to deploy: a. IBM cloud and b. kebernetes
3. github configuration steps in deploying to ibm cloud is missing.
4. Step 4 in  IBM cloud deploy needs to be elaborated. Even after doing that the deployment steps fails. choosing cloudfoundry or kubernetes as deployment type also fails.
<img width="1188" alt="screen shot 2018-03-27 at 9 35 55 pm" src="https://user-images.githubusercontent.com/1693915/38005604-fc98cc30-3206-11e8-8412-3f610641ae3b.png">

5.  There are common/redundant steps in both deployment ways which can be abstracted.
6. Steps section is only for "deploying using kubernetes" . Need to have steps for IBM cloud deploy as well.

**Comment by stevemar** [comment]
i believe this was fixed by making it a CF only app
