### ISSUE TITLE
rework code to only use natural language understanding

### ISSUE THREAD

**Issue by stevemar** [IBM/watson-second-opinion#38]
After speaking with our Discovery OM (Deepika Devarajan) we realized that the application was made unnecessarily complicated by using Discovery. This application could entirely be done with using Watson's Natural Language Understanding, a critical part of Discovery. Discovery buys us searchability and indexing of documents. But in this instance, we're simply showing results one at a time. We can make API calls to NLU, which provides the sentiment, tone, keywords, all the stuff we're showing in our UI. See https://natural-language-understanding-demo.ng.bluemix.net/ as an example.

The proposal here is to swap out the discovery bits for NLU. This will a) greatly speed up load time of initial products, b) simplify the code base since we'll remove a lot of logic for handling collections.

@horeaporutiu do you think you could do this, otherwise I will ask @rhagarty to take a whack at it.

**Comment by stevemar** [comment]
My hope is that we don't have to redo the video. Minimal changes to blog and README. The UI should not change since NLU will produce the same results.

**Comment by horeaporutiu** [comment]
@stevemart I can look at this next week. I'll work on converting to NLU. Thanks.

**Comment by stevemar** [comment]
thanks so much @horeaporutiu

**Comment by horeaporutiu** [comment]
@stevemart basic NLU working now (sentiment is hardcoded as of now, will change that tomorrow). Will continue to work on this until it is ready.

**Comment by stevemar** [comment]
@horeaporutiu any update on this one, did you need some help? can you post a PR?

**Comment by horeaporutiu** [comment]
@stevemart I have been pushing new code, and should have it done pretty soon. Hoping by end of next week. Only part that I really need to finish is the UI for desktop. (Mobile / tablet view works well). Also, I have just been committing to the repo without doing PR's lately (since I have mostly just changed the UI). I can start making PR's again, and have you review them before merging if you want. But either way shoud be done soon.

**Comment by stevemar** [comment]
@horeaporutiu i think this is closed now?

**Comment by horeaporutiu** [comment]
Yup. Just have to update the README and we should be good to go. Is the
video fine or should I do a different one?

**Comment by stevemar** [comment]
@horeaporutiu i think it's fine. The gist of it hasn't changed. You've already put in a ton of work and I don't want you to feel obligated to put in even more.

**Comment by horeaporutiu** [comment]
Ok. I’ll go ahead and just clean up the readme and I think we should be all
good!

**Comment by stevemar** [comment]
@horeaporutiu thanks! one comment about the new UI -- if you're including links at the top, i'd have one back to this github repo :)

**Comment by stevemar** [comment]
resolved
