### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by dcary01** [IBM/watson-second-opinion#47]
I can't seem to find the config.json.sample file. I'm also having issues using the term "export", I have tried to use "set" instead. Either way, I can't get the app to work, because I can't put in my credentials. Please help.

**Comment by horeaporutiu** [comment]
Thanks for bringing this up - the credentials system changed for Watson Natural Language Processing, so will have to update the steps accordingly.

**Comment by stevemar** [comment]
@dcary01 can you reference which step in the README you are referring to? Which OS are you using?

**Comment by horeaporutiu** [comment]
@dcary01 

I have now updated the instructions. You do not need config.json.sample. 

Instead, after you run npm install, you need to create Cloudant DB and Natural Language Understanding services. After that, you need to save the URL value from cloudant credentials (after creating new credentials) and IAM_APIKEY value from natural language understanding (after creating new credentials).

Next you need to feed those credentials to the app by using environmental variables. The way to do that is to do something like this, directly into your command line (make sure you are in watson-second-opinion directory) and run the following commands (use your own credentials):

```
watson-second-opinion$ export IAM_APIKEY=xJLkOtKCXISqQHwjfdRBb99u2r-5sJ7n_sEsfsTJXZiJ
watson-second-opinion$ export CLOUDANT_URL=https://c1a36a28-4ae2-4ff4-abab-d70a084a43f0-bluemix:d68d5073a344aa2f45ad30838e7c528ea8fbb163dd66ac1468612455e1fe6f26@c1a36a28-4ae2-4ff4-abab-d70a084a43f0-bluemix.cloudantnosqldb.appdomain.cloud
watson-second-opinion$ node app.js
```

After you run node app.js if all is well, you can go to localhost:4000 in the browser and start the app. I just started mine, so i know it works! Hope this helps. Let me know if you have any other questions.

**Comment by horeaporutiu** [comment]
@dcary01 I updated to source code to use the updated env variables (IAM_APIKEY and CLOUDANT URL) so please do a git pull origin master before trying to run the app. 

(i.e. pull latest version of the code, I updated it a couple minutes ago)

**Comment by stevemar** [comment]
@horeaporutiu thank you as always for keeping this repo updated! 

@dcary01 please reopen if you run into any more issues.

Closing this one based of https://github.com/IBM/watson-second-opinion/commit/763bd6b15e5a2542ad0a8f06a5ce36b220ff755e
