### ISSUE TITLE
Job Processing in Background

### ISSUE THREAD

**Issue by AnthonyAmanse** [IBM/watson-second-opinion#9]
https://github.com/Automattic/kue

This can be useful. We could run our functions in the backround (from scraping, uploading to cloudant to discovery) since it takes a while for them to complete when doing a request on `/reviews/:reviewId`

**Comment by stevemar** [comment]
Given that https://github.com/IBM/watson-second-opinion/pull/23 merged and fixed some performance issues, do we still want to explore this option?

**Comment by horeaporutiu** [comment]
No, I would focus on other things before this issue. Such as keyword filtering, having the image there, and responsive UI.

**Comment by AnthonyAmanse** [comment]
Let's close this
